- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: us-east-1
      instance_type: t2.micro
      ami: ami-26ebbc5c  # Redhat
      keypair: pk-key # pem file name

  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         aws_access_key: "AKIAJKCHVVFVMFG7KMNA"
         aws_secret_key: "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"
         group: Kubectl  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: "Demo"
         instance_tags:
            Name: "Demo"
         vpc_subnet_id: "subnet-4303836c"
         assign_public_ip: yes
      register: ec2
    
    - debug:
        msg: "{{ item['private_ip'] }}"
      with_items: "{{ ec2.instances }}"

    - set_fact: ip_list= "[]"
   
    - name: Construct IP list
      set_fact: ip_list= "{{ ip_list }} + ['{{ item.private_ip }}']"
      with_items: "{{ ec2.instances }}"
 
    - debug:
        msg: "{{ ip_list }}"

   
    - name: Add all web instance IPs to host group
      add_host: hostname={{ item.public_ip }} groupname=webservers
      with_items: '{{ ec2.instances }}'

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: '{{ ec2.instances }}'
       

